#!/bin/bash

echo -e "\e[0;49;34m"
echo -e "______        _____                                                       "
echo -e "| ___ \      |_   _|                                                      "
echo -e "| |_/ /  ___   | |    ___   _ __ ___    ___   _ __  _ __   ___  __      __"
echo -e "| ___ \ / _ \  | |   / _ \ | '_ \` _ \  / _ \ | '__|| '__| / _ \ \ \ /\ / /"
echo -e "| |_/ /|  __/  | |  | (_) || | | | | || (_) || |   | |   | (_) | \ V  V / "
echo -e "\____/  \___|  \_/   \___/ |_| |_| |_| \___/ |_|   |_|    \___/   \_/\_/  "
echo -e "\e[0m"
echo ""
echo "Welcome on BeTomorrow's wargame server."
echo ""
echo -e "\e[1;49;31mPlease do not use heavy brute forces, first it is not necessary and"
echo -e "second it will degrade other users experience, so play nice...\e[0m"
echo ""
echo "All folders are not writeable but you can create a temp directory to work with using 'mktemp -d'"
echo "If you have any question ask david directly or through #wargames on slack"
echo ""
echo "Server is running an ubuntu 14.04 64bits and all level's binaries have compiled using"
echo "following flags:"
echo "       -g                               "
echo "       -m32                             "
echo "       -fno-stack-protector             "
echo "       -z norelro                       "
echo "       -z execstack                     "
echo "       -mpreferred-stack-boundary=4     "
echo ""
echo "For convenience a shell code to spawn a /bin/sh shell is available under /var/local/shellcode"
echo "but you are not required to use it. If needed you can find more of them here http://shell-storm.org/shellcode/"
echo ""
echo "Good luck & have fun."
echo ""