#!/usr/bin/python

import sys
import socket

prevpass = sys.argv[1]
nextpass = sys.argv[2]

enteredpass = sys.stdin.readline().strip() ### TCP

msg = "Wrong! Please enter the correct current password"

if enteredpass == prevpass:
    msg = "Correct!\n%s" % nextpass

print msg


sys.exit(0)